Add stopwords
bab2min/kiwipiepy pull request #60
Opened 2021-11-09 11:48 UTC by HyeJuSeon

안녕하세요.
#53 에서 논의한 stopwors 기능을 구현했습니다.

미리 말씀드린 것처럼 AI Hub, 모두의 말뭉치의 코퍼스를 이용해서 TF 상위 100개를 뽑아 stopwords.txt를 만들었습니다.
다만, 제안해 주신 인터페이스에서 아래와 같은 수정 사항이 있어 확인해 주시면 감사하겠습니다.

``` python
from kiwipiepy.utils import Stopwords
stopwords = Stopwords() # stopword

('김가네', 'NNP') in stopwords.word() # stopwords 내에 단어 포함 여부 테스트
```

2021-11-09 16:45 UTC, bab2min requested changes
@HyeJuSeon
기능들이 많은데 잘 구현해주셔서 감사합니다~!
대부분 문제 없지만, 일부 잠재적으로 문제가 될 수 있는 코드나 효율적인 방법이 있는듯해서 코멘트를 남겼습니다. 한번 찬찬히 살펴보시고 궁금하신거나 이견 있으시면 편하게 피드백 남겨주세요~

p.s. 앗, 추가로 `Stopwords` 클래스 내의 `load_stopwords`, `tag_exists`, `token_exists` 메서드는 외부에서 호출할 일이 없으므로, 이름 앞에 `_`를 붙여서 감추는게 좋아보여요.

cc. @hexists

2021-11-09 16:45 UTC, bab2min commented on test.py
> +    stopwords = Stopwords(f'{os.path.abspath(os.path.join(curpath, ".."))}/custom_stopwords.txt')
테스트를 위해서는 `custom_stopwords.txt` 파일도 필요하겠네요~ test_corpus 내에 위치시키고 코드도 해당 경로로 수정해주시면 좋을것 같습니다.

2021-11-09 16:45 UTC, bab2min commented on kiwipiepy/utils.py
> +        self.stopwords = self.load_stopwords(filename)
filename을 이렇게 받을 경우, relative path로 잡히기 때문에 다른 코드에서 `kiwipiepy`를 import해서 사용할 경우 해당 파일을 찾지 못할 가능성이 있습니다. (import해서 쓰는 코드의 cwd를 기준으로 `kiwipiepy/corpus/stopwords.txt`를 찾게 되거든요)

아래와 같이 `__file__` 변수와 `os.path` 라이브러리를 이용하면 현재 코드 파일이 위치한 경로(`dir_path`)를 얻을 수 있습니다. 이걸 바탕으로 `corpus/stopwords.txt` 파일을 읽어오는게 더 안정적이겠죠?
```
path = os.path.abspath(__file__)
dir_path = os.path.dirname(path)
```

단 이렇게 할 경우 `dir_path`값을 `__init__` 메서드의 default argument value로  넣을수가 없으므로, `__init__(self, filename=None)`와 같이 선언하고, `filename is None`인 경우에만 위의 `dir_path`로 교체하는 식으로 코드를 좀 고쳐야하겠네요.

2021-11-09 16:45 UTC, bab2min commented on kiwipiepy/utils.py
> +        return filtered_tokens
내장 filter 함수를 쓰면 더 효율적인 코드를 작성할 수 있습니다:
```python
def _is_not_stopword(token):
    return (token.form, token.tag) not in self.stopwords

return list(filter(_is_not_stopword, tokens))
```

2021-11-09 16:45 UTC, bab2min commented on kiwipiepy/utils.py
> +        return self.stopwords
```python
('김가네', 'NNP') in stopwords.word()
```
이 부분 때문에 `word(self)` 메소드를 구현하신것 같은데요,

```python
def __contains__(self, word):
    return word in self.stopword
```
이런 식으로 contains magic method를 구현하시면
```python
('김가네', 'NNP') in stopwords
```
와 같은 식으로 쓸 수 있습니다.

2021-11-10 18:50 UTC, HyeJuSeon commented on kiwipiepy/utils.py
> +        return stopwords
잘못된 입력이 들어왔을 때 발생하는 에러 메시지를 수정해서 raise 하는게 맞나요?

2021-11-11 06:32 UTC, bab2min commented on kiwipiepy/utils.py
> +        return stopwords
`form, tag = stopword.split('/')`에서 실패하는 경우만 잡아내서 에러메세지를 만들어주면 될거 같아요. 아래 같은 느낌으로요~?
```python
try:
 form, tag = stopword.split('/')
except:
  raise ValueError(f"Line in format 'form/tag' expected, but {repr(stopword)} found.")
```

2021-11-11 06:38 UTC, bab2min requested changes
@HyeJuSeon 
지금 다시 보니 `self.stopwords`도 list 타입으로 처리하고 있더라구요. 이것도 set 타입으로 바꾸는게 좋을거 같아서 추가 코멘트 남겼습니다~

2021-11-11 06:38 UTC, bab2min commented on kiwipiepy/utils.py
> +        self.stopwords = self._load_stopwords(filename)
지금 보니 `self.stopwords`도 list 타입으로 들어가네요~
`self.stopwords`에도 in 연산을 주로 사용할거니깐 `set()`타입을 쓰는게 좋겠습니다!

2021-11-11 06:38 UTC, bab2min commented on kiwipiepy/utils.py
>          self.stopwords = list(set(self.stopwords))
`self.stopwords`를 set 타입으로 바꾸면 여기서 굳이 `list(set(...))`로 중복제거를 할 필요도 없구요. `remove()` 메서드에서도 마찬가지입니다.

2021-11-11 14:39 UTC, HyeJuSeon commented on kiwipiepy/utils.py
> +        return stopwords
네 그렇게 수정하겠습니다!

2021-11-12 04:02 UTC, bab2min commented
@HyeJuSeon 
macOS에서 테스트에 실패하긴 했는데, 이건 stopwords 코드의 문제가 아니라 github workflows에서 제공하는 macOS 버전 변경으로 인한거네요~ 이부분 테스트는 통과한걸로 보고 머지 진행하도록 할게요!

2021-11-12 04:04 UTC, merged